"""
example_cs165cu.py
==================
Bayesian ratio pyrometry using the Thorlabs CS165CU camera without an IR
filter.

Procedure
---------
1. Load per-channel QE from the xlsx workbook.
2. Build a RatioPyrometer.  LUTs for all three RGB pairs are computed
   automatically:  (blue, red), (green, red), (green, blue).
3. Analyse a region-of-interest in the test image.  The library assumes
   the ROI is isothermal and combines every (pixel, pair) measurement
   into a single posterior on T* using a Gaussian noise model and a
   uniform prior.
4. Print summary statistics (MAP, mean +/- std, 68 / 95 % credible
   intervals) and produce figures:

    Figure 1 -- 3 x 3 grid (generated by pyrometer.plotting.plot_analysis):
    | row pair      | col 0 (ratio image + ROI) | col 1 (ROI histogram + LUT) | col 2 (log-likelihood) |
    | blue/red      | ratio map                  | hist & f_br(T) on twin y    | log L_br(T)            |
    | green/red     | ratio map                  | hist & f_gr(T) on twin y    | log L_gr(T)            |
    | green/blue    | ratio map                  | hist & f_gb(T) on twin y    | log L_gb(T)            |

    Figure 2 -- final log-posterior log pi_3(T).
    Figure 3 -- ROI-only ratio images (autoscaled per pair).

Edit the ROI tuple to surround the hot region in your image.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import openpyxl

HERE = Path(__file__).parent

from pyrometer import RatioPyrometer
from pyrometer.plotting import plot_analysis


XLSX_PATH = HERE / "cs165cu_quantum_efficiency.xlsx"
IMAGE_PATH = HERE / "test.ppm"


# ---------------------------------------------------------------------------
# 1.  Load QE data
# ---------------------------------------------------------------------------

wb = openpyxl.load_workbook(XLSX_PATH, data_only=True)
ws = wb["Quantum Efficiency"]
rows = [r for r in ws.iter_rows(min_row=4, values_only=True)
        if isinstance(r[2], (int, float))]
wl_nm = np.array([r[2] for r in rows], dtype=float)   # 400-1000 nm, 5 nm step
qe_b  = np.array([r[3] for r in rows], dtype=float)   # %
qe_g  = np.array([r[4] for r in rows], dtype=float)   # %
qe_r  = np.array([r[5] for r in rows], dtype=float)   # %

print(f"QE loaded: {len(wl_nm)} points, {wl_nm[0]:.0f}-{wl_nm[-1]:.0f} nm")


# ---------------------------------------------------------------------------
# 2.  Build the pyrometer  (LUTs for all 3 pairs are computed automatically)
# ---------------------------------------------------------------------------

pyro = RatioPyrometer(
    wavelengths_nm=wl_nm,
    qe_channels={"red": qe_r, "green": qe_g, "blue": qe_b},
    t_range=(500.0, 2500.0),
    n_temps=1000,
    # ir_filter=None  <-- default: full transmission (filter physically removed)
)

print("\nLUTs (in sequential-update order):")
for ci, cj in pyro.pairs:
    R = pyro.ratio_lut[(ci, cj)]
    print(f"  {ci}/{cj:<5s}  {pyro.monotonic_direction[(ci, cj)]:<14s}  "
          f"LUT range [{R.min():.4f}, {R.max():.4f}]")


# ---------------------------------------------------------------------------
# 3.  Analyse the ROI
# ---------------------------------------------------------------------------

ROI = (600, 830, 800, 1000)   # (row0, row1, col0, col1) -- edit to your hot region

result = pyro.analyze(
    image=IMAGE_PATH,
    roi=ROI,
    channel_order=("red", "green", "blue"),
    wb_red=1.0,
    wb_blue=1.0,
    # CS165CU 8-bit defaults already set: read_noise_dn=0.86, gain=2.72, max_dn=255
)

print(f"\nROI {ROI}  ({ROI[1] - ROI[0]} x {ROI[3] - ROI[2]} px)")
for pair in pyro.pairs:
    print(f"  {pair[0]}/{pair[1]:<5s}: "
          f"{result.n_valid_pixels_per_pair[pair]:6d} valid pixels")

# Extract summary statistics from the first posterior pi_1(T).
T_grid = result.temperatures_grid
first_posterior = result.posterior_sequential[1]
map_idx = int(np.argmax(first_posterior))
map_T = float(T_grid[map_idx])
mean_T = float(np.trapezoid(T_grid * first_posterior, T_grid))
var_T = float(np.trapezoid((T_grid - mean_T) ** 2 * first_posterior, T_grid))
std_T = float(np.sqrt(max(var_T, 0.0)))
ci_68 = pyro._hdi(first_posterior, T_grid, 0.68)
ci_95 = pyro._hdi(first_posterior, T_grid, 0.95)
print()
print(f"Summary statistics from pair "
      f"{pyro.pairs[0][0]}/{pyro.pairs[0][1]:<5s} only:")
print(f"MAP temperature        : {map_T:7.1f} K  "
      f"({map_T - 273.15:.1f} deg C)")
print(f"Posterior mean +/- std : {mean_T:7.1f} +/- "
      f"{var_T:.1f} K")
print(f"68% credible interval  : [{ci_68[0]:.1f}, {ci_68[1]:.1f}] K")
print(f"95% credible interval  : [{ci_95[0]:.1f}, {ci_95[1]:.1f}] K")

# Print summary statistics from all three pairs combined
print()
print(f"Summary statistics from all three pairs combined:")
print(f"MAP temperature        : {result.map_temperature:7.1f} K  "
      f"({result.map_temperature - 273.15:.1f} deg C)")
print(f"Posterior mean +/- std : {result.mean_temperature:7.1f} +/- "
      f"{result.std_temperature:.1f} K")
print(f"68% credible interval  : [{result.ci_68[0]:.1f}, {result.ci_68[1]:.1f}] K")
print(f"95% credible interval  : [{result.ci_95[0]:.1f}, {result.ci_95[1]:.1f}] K")

print(f"\nGoodness of fit at joint MAP (chi^2_red ~= 1 => model fits the noise):")
for pair in pyro.pairs:
    chi2 = result.chi2_per_pair[pair]
    chi2r = result.reduced_chi2_per_pair[pair]
    n = result.n_valid_pixels_per_pair[pair]
    print(f"  {pair[0]}/{pair[1]:<5s}: "
          f"chi^2 = {chi2:11.3e},  N = {n:6d},  chi^2/N = {chi2r:.2f}")
print(f"  total       : chi^2/dof = {result.reduced_chi2_total:.2f}")


# ---------------------------------------------------------------------------
# 4.  Figure 1: standard 3 x 3 analysis figure
# ---------------------------------------------------------------------------

fig1 = plot_analysis(result, pyro, IMAGE_PATH, ROI)
fig1.savefig(HERE / "pyrometry_result.png", dpi=150)
print(f"\nFigure saved -> {HERE / 'pyrometry_result.png'}")


# ---------------------------------------------------------------------------
# 5.  Figure 2: final log-posterior pi_3(T)
# ---------------------------------------------------------------------------

print(f"\nPer-pair log-likelihood peak temperatures:")
for pair in pyro.pairs:
    log_L = result.pair_log_likelihoods[pair]
    T_peak = float(result.temperatures_grid[int(np.argmax(log_L))])
    print(f"  {pair[0]}/{pair[1]:<5s}: {T_peak:7.2f} K")

T_grid = result.temperatures_grid

fig2, ax2 = plt.subplots(figsize=(9, 5))
log_pi_final = np.log(np.maximum(result.posterior, 1e-300))
log_pi_final = log_pi_final - log_pi_final.max()    # shift peak to 0
ax2.plot(T_grid, log_pi_final, color="darkorange", lw=1.8)
ax2.axvline(result.map_temperature, color="red", lw=1.0,
            label=f"MAP = {result.map_temperature:.1f} K")
ax2.axvspan(result.ci_68[0], result.ci_68[1],
            color="red", alpha=0.15,
            label=f"68% CI [{result.ci_68[0]:.1f}, {result.ci_68[1]:.1f}] K")
ax2.set_xlim(T_grid.min(), T_grid.max())
ax2.set_ylim(-3000.0, 100.0)
ax2.set_xlabel("Temperature (K)")
ax2.set_ylabel(r"$\log \pi_3(T) - \max$")
ax2.set_title(
    f"Final log-posterior after fusing all three pairs  --  "
    f"sigma = {result.std_temperature:.1f} K (statistical)"
)
ax2.grid(True, alpha=0.3)
ax2.legend(loc="lower right", fontsize=9)
fig2.tight_layout()
fig2.savefig(HERE / "final_posterior.png", dpi=150)
print(f"Figure saved -> {HERE / 'final_posterior.png'}")


# ---------------------------------------------------------------------------
# 6.  Figure 3: ROI-only ratio images (autoscaled per pair)
# ---------------------------------------------------------------------------

r0, r1, c0, c1 = ROI

fig3, axes3 = plt.subplots(1, 3, figsize=(15, 4.5))
for ax3, pair in zip(axes3, pyro.pairs):
    ci, cj = pair
    label = f"{ci}/{cj}"
    ratio_roi = result.ratio_images[pair][r0:r1, c0:c1]
    valid = ratio_roi[np.isfinite(ratio_roi)]
    if valid.size:
        vmin = float(np.percentile(valid, 2))
        vmax = float(np.percentile(valid, 98))
    else:
        vmin, vmax = 0.0, 1.0
    im3 = ax3.imshow(ratio_roi, cmap="viridis", vmin=vmin, vmax=vmax)
    plt.colorbar(im3, ax=ax3, label=label, fraction=0.046, pad=0.04)
    ax3.set_title(
        f"{label}  ROI ratio   (min {valid.min():.3f}, max {valid.max():.3f})"
        if valid.size else f"{label} ROI ratio"
    )
    ax3.set_xticks([])
    ax3.set_yticks([])

fig3.suptitle(
    "ROI-only ratio images (each auto-scaled).  "
    "Spatial variations here imply spatial T gradients.",
    fontsize=11,
)
fig3.tight_layout()
fig3.savefig(HERE / "roi_ratio_images.png", dpi=150)
print(f"Figure saved -> {HERE / 'roi_ratio_images.png'}")


if "--no-show" not in sys.argv:
    plt.show()
